### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by evgeny92** [laravelista/multilingual-web-application-with-laravel#1]
Hello! I cloned the project and get error when I create an article. 
Error:
```
ErrorException in 65256e983521b336da0b3e41dad3e7d8883e8b4f.php line 18:
Trying to get property of non-object (View: /var/www/l-multilingual/resources/views/articles/index.blade.php)
```

**Comment by mabasic** [comment]
I think I know where is the problem. The repo seems to be missing a config file translatable.php. 

Will fix this today and let you know.

**Comment by evgeny92** [comment]
Thanks, I'll wait.

**Comment by mabasic** [comment]
Oh, awesome! I was just going to write that it will take me a few days to do that because i just became an uncle for the second time.

**Comment by evgeny92** [comment]
It's fine))

**Comment by evgeny92** [comment]
I am sorry for my question, please tell me what it means in the controller: $request->get('translation')[$locale]['title'] and in blade/form/input/:  name="translation[{{$locale}}][title]", I do not understand what it means 'translation'...

**Comment by mabasic** [comment]
In the controller that means:
- get from request parameter called "translation['en']['title']"

In the view file that means:
- set the input name to array called "translation['en']['title']"

I could have written this differently. See the docs for accessing array inputs: https://laravel.com/docs/5.6/requests#retrieving-input

**Comment by evgeny92** [comment]
Thanks, now I understand.
